import type { EcgReport } from './db';

type AiInterpretation = NonNullable<EcgReport['aiInterpretation']>;

const defaultDisclaimer =
  'This interpretation is generated by an AI model for educational purposes only. It does not constitute medical advice, diagnosis, or treatment.';

function parseMaybeJson(value: unknown): unknown {
  if (typeof value !== 'string') return value;

  const trimmed = value.trim();
  if (!trimmed) return null;

  const unfenced = trimmed
    .replace(/^```(?:json)?\s*/i, '')
    .replace(/```$/i, '')
    .trim();

  try {
    return JSON.parse(unfenced);
  } catch {
    return { primaryInterpretation: unfenced, stepByStepInterpretation: unfenced };
  }
}

function unwrapInterpretationPayload(value: unknown): any {
  const parsed = parseMaybeJson(value) as any;
  if (!parsed || typeof parsed !== 'object') return null;

  return (
    parseMaybeJson(parsed.interpretation) ||
    parseMaybeJson(parsed.aiInterpretation) ||
    parseMaybeJson(parsed.data?.interpretation) ||
    parseMaybeJson(parsed.result?.interpretation) ||
    parsed
  );
}

export function normalizeAiInterpretation(value: unknown): AiInterpretation | null {
  const ai = unwrapInterpretationPayload(value);
  if (!ai || typeof ai !== 'object') return null;

  const primaryInterpretation = ai.primaryInterpretation || ai.primary || ai.summary;
  const stepByStepInterpretation = ai.stepByStepInterpretation || ai.stepByStep || ai.summary || primaryInterpretation;
  const differentialsAndExplanation = ai.differentialsAndExplanation || ai.differentials || ai.possibleFindings;
  const nextSteps = {
    investigations: ai.nextSteps?.investigations || ai.investigations || '',
    management: ai.nextSteps?.management || ai.management || ai.nextSteps || '',
  };

  const hasMeaningfulContent = [
    primaryInterpretation,
    stepByStepInterpretation,
    differentialsAndExplanation,
    ai.dangerousFindings,
    ai.missingDataWarnings,
    ai.teachingExplanation || ai.educationalNotes,
  ].some((field) => typeof field === 'string' && field.trim().length > 0);

  if (!hasMeaningfulContent) return null;

  const normalized: AiInterpretation = {
    primaryInterpretation: primaryInterpretation || stepByStepInterpretation,
    dangerousFindings: ai.dangerousFindings || 'No dangerous-finding assessment was provided.',
    missingDataWarnings: ai.missingDataWarnings || 'No missing-data warning was provided.',
    urgencyLevel: ai.urgencyLevel || 'insufficient_data',
    teachingExplanation: ai.teachingExplanation || ai.educationalNotes || '',
    stepByStepInterpretation,
    differentialsAndExplanation: differentialsAndExplanation || 'No differential explanation was provided.',
    nextSteps,
    disclaimer: ai.disclaimer || defaultDisclaimer,
  };

  const rawResponse = typeof value === 'string' ? value : ai.rawResponse;
  if (typeof rawResponse === 'string' && rawResponse.trim().length > 0) {
    normalized.rawResponse = rawResponse;
  }

  return normalized;
}

export function hasGeneratedAiInterpretation(value: unknown) {
  return normalizeAiInterpretation(value) !== null;
}
