import type { LearningTopicId } from './ecgLearning';

export type EcgStudyStep = {
  step: number;
  title: string;
  focus: string;
  topicId: LearningTopicId;
  checkpoints: string[];
  clinicalPearl: string;
};

export type RedFlagTrainerItem = {
  id: string;
  title: string;
  urgency: string;
  cue: string;
  risk: string;
  action: string;
  pattern: string[];
  immediateActions: string[];
  clinicalTips: string[];
  mimics: { name: string; differentiation: string }[];
  topicId: LearningTopicId;
};

export type EcgConditionItem = {
  id: string;
  title: string;
  category: string;
  definition: string;
  pathophysiology: string;
  symptoms: string[];
  criteria: { label: string; value: string }[];
  pearls: string[];
  topicId: LearningTopicId;
};

export const ecgStudySources = [
  'ECGs Made Easy, 6th ed.',
  'ECG Interpretation Made Incredibly Easy!, 5th ed.',
  'ECG in 10 Days, 2nd ed.',
] as const;

export const redFlagTrainerItems: RedFlagTrainerItem[] = [
  {
    id: 'stemi-omi',
    title: 'STEMI / OMI equivalents',
    urgency: 'Emergent / time-critical',
    cue: 'Territorial ST elevation, reciprocal change, posterior/RV clues, or hyperacute T waves with ischemic symptoms.',
    risk: 'Acute coronary occlusion can be time-critical even when the pattern is subtle or not a classic STEMI label.',
    action: 'Check contiguous leads, reciprocal changes, symptoms, serial ECGs, and posterior/right-sided leads when indicated.',
    pattern: [
      'ST elevation in two or more contiguous leads, with V2-V3 using sex- and age-specific thresholds.',
      'Reciprocal ST depression in anatomically opposite leads increases concern for acute occlusion.',
      'Hyperacute broad T waves, posterior ST depression in V1-V3, or right ventricular involvement can be OMI clues before a classic label appears.',
    ],
    immediateActions: [
      'Assess symptoms, hemodynamics, and serial ECG change immediately.',
      'Escalate for urgent reperfusion pathway when occlusion MI is suspected.',
      'Use posterior or right-sided leads when the standard 12-lead pattern suggests hidden territory involvement.',
    ],
    clinicalTips: [
      'Inferior STEMI can involve the right ventricle; nitrates may cause severe hypotension when preload is dependent.',
      'Compare with prior ECGs when LBBB, LVH, or chronic repolarisation changes are present.',
    ],
    mimics: [
      {
        name: 'Acute pericarditis',
        differentiation: 'Usually produces diffuse concave ST elevation with PR depression rather than a focal coronary territory with reciprocal changes.',
      },
      {
        name: 'LBBB or LVH strain',
        differentiation: 'Secondary ST-T changes follow QRS polarity; prior ECG comparison and concordance rules help separate chronic strain from acute occlusion.',
      },
    ],
    topicId: 'step.stSegment',
  },
  {
    id: 'complete-heart-block',
    title: 'Complete heart block',
    urgency: 'Emergent / symptomatic bradycardia',
    cue: 'Independent P waves and QRS complexes with atrial and ventricular rates marching separately.',
    risk: 'Unstable bradycardia, syncope, escape rhythm failure, and need for urgent pacing assessment.',
    action: 'Compare atrial and ventricular rates, verify PR variability, inspect QRS width, and escalate if symptomatic.',
    pattern: [
      'P-P intervals are regular and R-R intervals are regular, but P waves have no fixed relationship to QRS complexes.',
      'PR intervals are completely variable because atria and ventricles are electrically dissociated.',
      'Escape rhythm may be narrow if junctional or wide and slower if ventricular.',
    ],
    immediateActions: [
      'Assess blood pressure, mentation, chest pain, shock, and syncope.',
      'Prepare for transcutaneous pacing if unstable or if escape rhythm is very slow.',
      'Use atropine cautiously and do not delay pacing in high-risk presentations.',
    ],
    clinicalTips: [
      'Both atrial and ventricular rhythms can be regular, which helps distinguish complete block from Mobitz I.',
      'A wide escape rhythm usually means a lower escape focus and higher instability risk.',
    ],
    mimics: [
      {
        name: 'Mobitz I AV block',
        differentiation: 'Mobitz I has progressive PR lengthening before a dropped QRS; complete block has no consistent PR relationship.',
      },
      {
        name: 'AV dissociation with accelerated junctional rhythm',
        differentiation: 'Rates may be close together; look for capture/fusion beats and whether atrial impulses ever conduct.',
      },
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'mobitz-ii',
    title: 'Mobitz II AV block',
    urgency: 'High risk / pacing concern',
    cue: 'Fixed conducted PR intervals with intermittent dropped QRS complexes.',
    risk: 'High-grade conduction disease with risk of progression to complete heart block.',
    action: 'Do not dismiss as benign Wenckebach; check dropped-beat pattern, QRS width, symptoms, and medications.',
    pattern: [
      'Conducted beats have a constant PR interval.',
      'Intermittent P waves fail to conduct, causing sudden dropped QRS complexes.',
      'QRS may be wide when disease is infranodal, increasing concern for progression.',
    ],
    immediateActions: [
      'Escalate urgently if syncope, hypotension, chest pain, heart failure, or a slow ventricular rate is present.',
      'Review AV nodal blockers, ischemia, and electrolyte context, but do not let reversible causes delay safety planning.',
      'Prepare for pacing assessment in symptomatic or high-grade patterns.',
    ],
    clinicalTips: [
      'A fixed PR before dropped beats is the key teaching distinction from Wenckebach.',
      '2:1 AV block can hide whether the mechanism is Mobitz I or II; QRS width and clinical context matter.',
    ],
    mimics: [
      {
        name: 'Mobitz I Wenckebach',
        differentiation: 'PR intervals progressively lengthen before the dropped beat and the grouped rhythm is often irregular.',
      },
      {
        name: 'Blocked premature atrial complexes',
        differentiation: 'A premature hidden P wave may deform the preceding T wave and create a pause that mimics AV block.',
      },
    ],
    topicId: 'step.prInterval',
  },
  {
    id: 'wide-complex-tachycardia',
    title: 'Wide-complex tachycardia',
    urgency: 'Critical if unstable',
    cue: 'Fast rhythm with QRS duration at least 0.12 seconds, especially with AV dissociation or concordance.',
    risk: 'Ventricular tachycardia until proven otherwise in many clinical contexts.',
    action: 'Treat uncertain WCT cautiously, review V1/V6 morphology, concordance, capture/fusion beats, and stability.',
    pattern: [
      'Rate often 101-250 bpm with QRS duration at least 0.12 seconds.',
      'Monomorphic VT is usually regular with wide, bizarre QRS complexes of uniform shape.',
      'AV dissociation, capture beats, fusion beats, and precordial concordance strongly support VT.',
    ],
    immediateActions: [
      'Check pulse and hemodynamic stability immediately.',
      'If pulseless, treat as VF/pulseless VT with CPR and defibrillation.',
      'If unstable with a pulse, follow synchronized cardioversion pathway.',
    ],
    clinicalTips: [
      'A rapid wide rhythm with shock, chest pain, heart failure, or syncope should be presumed VT until proven otherwise.',
      'Do not rely on a single lead; compare V1, V6, axis, concordance, and clinical context.',
    ],
    mimics: [
      {
        name: 'SVT with aberrancy',
        differentiation: 'Can look similar to VT when baseline BBB exists; instability or uncertainty should be managed cautiously as VT.',
      },
      {
        name: 'Pre-excited atrial fibrillation',
        differentiation: 'Often irregularly irregular, very rapid, and wide; AV nodal blockers can be dangerous.',
      },
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'hyperkalemia',
    title: 'Hyperkalemia',
    urgency: 'Emergent / metabolic emergency',
    cue: 'Tall narrow tented T waves, PR prolongation, QRS widening, or sine-wave progression.',
    risk: 'Rapid deterioration into malignant arrhythmia or cardiac arrest.',
    action: 'Correlate potassium, renal history, medications, QRS width, and escalating ECG changes urgently.',
    pattern: [
      'Tall, narrow, symmetric tented T waves may be the earliest ECG sign.',
      'Progression can include PR prolongation, flattened or absent P waves, QRS widening, and sine-wave morphology.',
      'ECG severity may not perfectly match potassium level, so lab and clinical correlation are essential.',
    ],
    immediateActions: [
      'Escalate immediately when QRS widening, bradycardia, weakness, renal failure, or severe potassium elevation is suspected.',
      'Stabilise myocardium with IV calcium when clinically indicated.',
      'Shift potassium intracellularly and arrange potassium removal according to local protocol.',
    ],
    clinicalTips: [
      'Peaked T waves from hyperkalemia are usually narrow, symmetric, and diffuse.',
      'QRS narrowing after calcium is a useful sign of membrane stabilisation.',
    ],
    mimics: [
      {
        name: 'Hyperacute T waves of early MI',
        differentiation: 'Hyperacute ischemic T waves are broader, more bulky, and territory-based rather than narrow and diffuse.',
      },
      {
        name: 'Normal tall T waves in young patients',
        differentiation: 'Clinical context, serial change, QRS/PR effects, and potassium level separate benign voltage from metabolic danger.',
      },
    ],
    topicId: 'step.tWaves',
  },
  {
    id: 'long-qt-torsades',
    title: 'Long QT / torsades risk',
    urgency: 'Critical / arrhythmia risk',
    cue: 'QTc above 500 ms, pause-dependent ectopy, R-on-T beats, or QT-prolonging drug/electrolyte context.',
    risk: 'Torsades de pointes and sudden ventricular arrhythmia.',
    action: 'Recheck QT endpoint, rate correction, QRS width, potassium/magnesium/calcium, and QT-prolonging medicines.',
    pattern: [
      'QTc above 500 ms is a major safety threshold for torsades risk.',
      'Torsades appears as polymorphic VT with wide complexes twisting around the baseline.',
      'R-on-T ectopy, bradycardia pauses, hypokalemia, hypomagnesemia, hypocalcemia, and QT-prolonging drugs increase risk.',
    ],
    immediateActions: [
      'If torsades is pulseless, start CPR and defibrillate.',
      'If torsades has a pulse, magnesium sulfate is first-line while correcting electrolytes and stopping QT-prolonging drugs.',
      'Recheck QT measurement boundaries, especially when U waves are present.',
    ],
    clinicalTips: [
      'Bazett correction can overcorrect in tachycardia and undercorrect in bradycardia.',
      'Large U waves can be mistaken for the T-wave end and falsely prolong QTc.',
    ],
    mimics: [
      {
        name: 'Monomorphic VT with artifact',
        differentiation: 'Torsades changes amplitude and polarity in a spindle pattern; monomorphic VT keeps a uniform QRS shape.',
      },
      {
        name: 'Apparent long QT from U waves',
        differentiation: 'Look for a baseline return between T and U waves before deciding where the QT ends.',
      },
    ],
    topicId: 'step.qtInterval',
  },
  {
    id: 'brugada',
    title: 'Brugada pattern',
    urgency: 'High risk if symptomatic',
    cue: 'Coved ST elevation with T-wave inversion in V1-V3, often with RBBB-like appearance.',
    risk: 'Potential malignant ventricular arrhythmia risk, especially with syncope, fever, or family history.',
    action: 'Review right precordial leads, exclude mimics, document symptoms/family history, and escalate concerning cases.',
    pattern: [
      'Type 1 pattern has coved ST elevation in V1-V3 followed by T-wave inversion.',
      'It can resemble RBBB but the clinical concern is sodium-channel related ventricular arrhythmia risk.',
      'Fever, sodium-channel blockers, and electrolyte disturbance can unmask or worsen the pattern.',
    ],
    immediateActions: [
      'Escalate urgently when Brugada pattern is paired with syncope, nocturnal agonal respiration, ventricular arrhythmia, fever, or family history of sudden death.',
      'Treat fever and review provoking medications or metabolic triggers.',
      'Document right precordial lead placement and consider high intercostal V1-V2 recordings when advised locally.',
    ],
    clinicalTips: [
      'The ECG pattern alone is not the whole diagnosis; symptoms and family history drive risk.',
      'Lead placement matters because high right precordial leads can reveal the pattern more clearly.',
    ],
    mimics: [
      {
        name: 'RBBB with secondary ST-T change',
        differentiation: 'True Brugada type 1 has coved ST elevation and T inversion in the right precordial leads rather than ordinary discordant repolarisation alone.',
      },
      {
        name: 'Anterior ischemia or early repolarisation',
        differentiation: 'Use symptoms, serial ECGs, reciprocal changes, and clinical context to avoid mislabelling ST elevation.',
      },
    ],
    topicId: 'step.lateWaves',
  },
  {
    id: 'vfib',
    title: 'Ventricular fibrillation',
    urgency: 'Critical / cardiac arrest',
    cue: 'Chaotic irregular waveform with no organised QRS complexes, P waves, or pulse-generating rhythm.',
    risk: 'No coordinated ventricular contraction means zero cardiac output and immediate collapse.',
    action: 'Check patient and leads, start CPR, and defibrillate rapidly if true VF is confirmed.',
    pattern: [
      'Rate is indeterminate with rapid disorganised impulses.',
      'No measurable P waves, PR interval, QRS complexes, or T waves.',
      'Coarse VF has larger fibrillatory waves; fine VF can approach a flatline appearance.',
    ],
    immediateActions: [
      'Check responsiveness and pulse immediately.',
      'Begin high-quality CPR and deliver unsynchronised defibrillation for true VF.',
      'Verify in more than one lead while avoiding delays in cardiac arrest care.',
    ],
    clinicalTips: [
      'Always check the patient to avoid shocking artifact from movement, shivering, or disconnected leads.',
      'Fine VF can be mistaken for asystole; increasing gain or checking another lead may reveal fibrillatory activity.',
    ],
    mimics: [
      {
        name: 'Severe muscle tremor or shivering',
        differentiation: 'The patient is usually conscious with a pulse, and an underlying rhythm may appear after repositioning leads.',
      },
      {
        name: '60-cycle interference',
        differentiation: 'Creates a uniform fuzzy baseline; check cables, power cords, and electrode contact.',
      },
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'pea-asystole',
    title: 'PEA / asystole check',
    urgency: 'Critical / cardiac arrest',
    cue: 'Organised electrical rhythm without a pulse, or true flatline with no ventricular electrical activity.',
    risk: 'Both represent cardiac arrest physiology and require immediate CPR, but neither is treated with shock unless VF/VT is found.',
    action: 'Confirm pulse and leads, start CPR, give epinephrine per protocol, and search for reversible Hs and Ts.',
    pattern: [
      'PEA can show any organised rhythm on the monitor but no mechanical pulse.',
      'Asystole shows no ventricular electrical activity; occasional isolated P waves may be present.',
      'Lead disconnection and fine VF must be excluded quickly.',
    ],
    immediateActions: [
      'Check a central pulse immediately when an organised rhythm appears in an unresponsive patient.',
      'Start CPR and epinephrine pathway; do not shock true PEA or asystole.',
      'Search for reversible causes such as hypoxia, hypovolemia, acidosis, hyperkalemia, tamponade, tension pneumothorax, toxins, and thrombosis.',
    ],
    clinicalTips: [
      'PEA is the electrical-mechanical split: monitor rhythm is not enough without a physical pulse.',
      'Confirm asystole in at least two leads and check cable connections.',
    ],
    mimics: [
      {
        name: 'Fine ventricular fibrillation',
        differentiation: 'May look flat; gain adjustment or another lead can show fibrillatory waves, which are shockable.',
      },
      {
        name: 'Profound hypotension',
        differentiation: 'A pulse may be extremely weak; if no central pulse is felt in an unresponsive patient, begin CPR.',
      },
    ],
    topicId: 'step.finalReview',
  },
];

export const ecgConditionItems: EcgConditionItem[] = [
  {
    id: 'atrial-fibrillation',
    title: 'Atrial fibrillation',
    category: 'Supraventricular rhythm',
    definition: 'The most common sustained cardiac arrhythmia, caused by rapid chaotic atrial electrical activity.',
    pathophysiology: 'Multiple ectopic atrial foci bombard the atria, causing fibrillation rather than coordinated contraction. Loss of atrial kick can reduce cardiac output and increases atrial thrombus and embolic stroke risk.',
    symptoms: ['Fatigue', 'Irregular palpitations', 'Chest discomfort', 'Dizziness or lightheadedness', 'Dyspnea', 'Congestive heart failure signs'],
    criteria: [
      { label: 'Rhythm', value: 'Ventricular rhythm is irregularly irregular.' },
      { label: 'Rate', value: 'Atrial rate is rapid and not directly measurable, often 300-600 bpm; ventricular rate varies with AV conduction.' },
      { label: 'P waves', value: 'Absent and replaced by fine or coarse fibrillatory waves that distort the baseline.' },
      { label: 'PR interval', value: 'Indiscernible and not measurable.' },
      { label: 'QRS complex', value: 'Usually narrow unless bundle branch block or aberrant conduction is present.' },
    ],
    pearls: [
      'Do not diagnose AFib from irregularity alone; confirm absent organised P waves.',
      'A very rapid irregular wide-complex rhythm should raise concern for pre-excited AF.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'atrial-flutter',
    title: 'Atrial flutter',
    category: 'Supraventricular rhythm',
    definition: 'A supraventricular tachyarrhythmia with rapid regular atrial depolarisations from a macro-reentrant circuit.',
    pathophysiology: 'A reentry circuit, usually in the right atrium, drives atrial rates around 250-350 bpm. The AV node blocks some impulses, producing fixed or variable conduction ratios.',
    symptoms: ['Palpitations', 'Chest pain', 'Dyspnea', 'Lightheadedness', 'Exercise intolerance', 'Fatigue', 'Syncope'],
    criteria: [
      { label: 'Rhythm', value: 'Atrial rhythm is regular; ventricular rhythm is regular with fixed block or irregular with variable block.' },
      { label: 'Rate', value: 'Atrial rate typically 250-350 bpm; ventricular rate depends on conduction ratio.' },
      { label: 'P waves', value: 'No true P waves; regular sawtooth flutter waves, often best in II, III, and aVF.' },
      { label: 'PR interval', value: 'Not measurable.' },
      { label: 'QRS complex', value: 'Usually normal duration unless aberrancy or bundle branch block coexists.' },
    ],
    pearls: [
      'A ventricular rate near 150 bpm should make you actively look for 2:1 flutter.',
      'Variable block can make flutter appear irregular and mimic AFib.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'multifocal-atrial-tachycardia',
    title: 'Multifocal atrial tachycardia',
    category: 'Supraventricular rhythm',
    definition: 'An irregular rapid supraventricular rhythm produced by multiple atrial pacemakers firing above 100 bpm.',
    pathophysiology: 'Multiple wandering atrial foci are often triggered by advanced pulmonary disease, hypoxia, hypercapnia, or electrolyte depletion.',
    symptoms: ['Palpitations', 'Shortness of breath', 'Dizziness', 'Chest pain', 'Near-syncope'],
    criteria: [
      { label: 'Rhythm', value: 'Irregularly irregular.' },
      { label: 'Rate', value: 'Ventricular rate greater than 100 bpm, often 100-250 bpm.' },
      { label: 'P waves', value: 'At least three distinct P-wave morphologies in one lead.' },
      { label: 'PR interval', value: 'Variable from beat to beat.' },
      { label: 'QRS complex', value: 'Usually normal duration.' },
    ],
    pearls: [
      'MAT is AFib-like in irregularity but still has visible P waves.',
      'Always look for lung disease, hypoxia, and electrolyte triggers.',
    ],
    topicId: 'step.pWave',
  },
  {
    id: 'wolff-parkinson-white',
    title: 'Wolff-Parkinson-White syndrome',
    category: 'Pre-excitation',
    definition: 'A pre-excitation syndrome caused by an accessory pathway connecting atria and ventricles.',
    pathophysiology: 'The bundle of Kent bypasses AV nodal delay, activating part of the ventricle early and creating a substrate for AV reentrant tachycardia.',
    symptoms: ['Often asymptomatic', 'Sudden regular palpitations', 'Chest pressure', 'Dizziness', 'Dyspnea', 'Syncope'],
    criteria: [
      { label: 'PR interval', value: 'Short, less than 0.12 seconds.' },
      { label: 'Delta wave', value: 'Slurred initial QRS upstroke from early ventricular activation.' },
      { label: 'QRS complex', value: 'Widened beyond 0.11 seconds because of the delta wave.' },
      { label: 'ST-T changes', value: 'Secondary repolarisation changes usually point opposite the main QRS deflection.' },
    ],
    pearls: [
      'The classic triad is short PR, delta wave, and wide QRS.',
      'Irregular very rapid wide-complex tachycardia with pre-excitation is high risk.',
    ],
    topicId: 'step.prInterval',
  },
  {
    id: 'first-degree-av-block',
    title: 'First-degree AV block',
    category: 'AV conduction',
    definition: 'A conduction delay where every atrial impulse conducts to the ventricles but PR is prolonged.',
    pathophysiology: 'AV nodal conduction is slowed, often due to high vagal tone, drugs such as beta-blockers or digoxin, or degenerative nodal disease.',
    symptoms: ['Usually asymptomatic'],
    criteria: [
      { label: 'Rhythm', value: 'Atrial and ventricular rhythms are regular.' },
      { label: 'P waves', value: 'Upright and uniform, with each P followed by a QRS.' },
      { label: 'PR interval', value: 'Constant and longer than 0.20 seconds, or more than 5 small boxes.' },
      { label: 'QRS complex', value: 'Usually normal duration.' },
    ],
    pearls: [
      'It is a delay, not a dropped-beat block: every P wave conducts.',
      'Marked PR prolongation can still be clinically relevant when symptoms or medication toxicity are present.',
    ],
    topicId: 'step.prInterval',
  },
  {
    id: 'mobitz-i',
    title: 'Second-degree AV block type I',
    category: 'AV conduction',
    definition: 'Also called Wenckebach; progressive AV nodal delay until an atrial impulse is blocked.',
    pathophysiology: 'The AV node fatigues with repeated impulses, causing progressive PR lengthening until a P wave is not conducted, then the cycle resets.',
    symptoms: ['Often asymptomatic', 'Mild palpitations', 'Skipped-beat sensation', 'Lightheadedness', 'Dizziness'],
    criteria: [
      { label: 'Rhythm', value: 'Ventricular rhythm is irregular, often grouped beating.' },
      { label: 'Rate', value: 'Atrial rate is regular; ventricular rate is slower.' },
      { label: 'P waves', value: 'Normal P waves with intermittent non-conducted P waves.' },
      { label: 'PR interval', value: 'Progressively lengthens until a QRS drops; PR after the pause is shortest.' },
      { label: 'QRS complex', value: 'Usually normal duration.' },
    ],
    pearls: [
      'The progressive PR pattern is the key differentiator from Mobitz II.',
      'Grouped beating is a useful visual clue.',
    ],
    topicId: 'step.prInterval',
  },
  {
    id: 'mobitz-ii-condition',
    title: 'Second-degree AV block type II',
    category: 'AV conduction',
    definition: 'A high-risk incomplete AV block with sudden failed conduction and no preceding PR prolongation.',
    pathophysiology: 'Usually infranodal disease in the His-Purkinje system, where conduction is all-or-nothing and can suddenly fail.',
    symptoms: ['Dizziness', 'Lightheadedness', 'Syncope', 'Chest pain', 'Hypotension', 'Dyspnea'],
    criteria: [
      { label: 'Rhythm', value: 'Atrial rhythm is regular; ventricular rhythm is irregular unless fixed block is present.' },
      { label: 'Rate', value: 'Atrial rate is regular; ventricular rate is slow.' },
      { label: 'P waves', value: 'Normal P waves with sudden non-conducted P waves.' },
      { label: 'PR interval', value: 'Constant on conducted beats with no progressive lengthening.' },
      { label: 'QRS complex', value: 'May be narrow but is often wide due to bundle branch disease.' },
    ],
    pearls: [
      'Mobitz II is not benign Wenckebach; progression to complete block is the concern.',
      'A wide QRS makes infranodal disease more likely.',
    ],
    topicId: 'step.prInterval',
  },
  {
    id: 'third-degree-av-block-condition',
    title: 'Third-degree AV block',
    category: 'AV conduction',
    definition: 'Complete failure of conduction between atria and ventricles, with independent chamber pacing.',
    pathophysiology: 'All supraventricular impulses are blocked at the AV node, His bundle, or bundle branches; an escape pacemaker drives the ventricles independently.',
    symptoms: ['Profound bradycardia', 'Severe hypotension', 'Syncope', 'Chest pain', 'Dyspnea', 'Confusion', 'Cardiogenic shock'],
    criteria: [
      { label: 'Rhythm', value: 'P-P and R-R intervals are regular but independent.' },
      { label: 'Rate', value: 'Atrial rate often 60-100 bpm; ventricular escape 40-60 bpm if junctional or 20-40 bpm if ventricular.' },
      { label: 'P waves', value: 'Normal P waves march through without a constant QRS relationship.' },
      { label: 'PR interval', value: 'Completely variable.' },
      { label: 'QRS complex', value: 'Narrow with junctional escape or wide with ventricular escape.' },
    ],
    pearls: [
      'Regular P waves plus regular QRS complexes can still be complete block if they are dissociated.',
      'A wide slow escape rhythm is especially concerning.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'right-bundle-branch-block',
    title: 'Right bundle branch block',
    category: 'Ventricular conduction',
    definition: 'Delayed or blocked conduction down the right bundle branch, delaying right ventricular depolarisation.',
    pathophysiology: 'The left ventricle depolarises first; the impulse then spreads cell-to-cell across the septum to activate the right ventricle late.',
    symptoms: ['Often asymptomatic', 'May reflect septal ischemia', 'May occur with pulmonary embolism', 'May reflect degenerative conduction disease'],
    criteria: [
      { label: 'QRS duration', value: '0.12 seconds or more.' },
      { label: 'Lead V1', value: 'rSR prime pattern, rabbit ears, or M pattern with tall terminal R prime.' },
      { label: 'Lead V6', value: 'Wide slurred S wave.' },
      { label: 'ST-T changes', value: 'Secondary ST depression and T-wave inversion can appear in V1.' },
    ],
    pearls: [
      'The terminal R prime in V1 represents delayed right ventricular activation.',
      'New RBBB with ischemic symptoms deserves clinical correlation.',
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'left-bundle-branch-block',
    title: 'Left bundle branch block',
    category: 'Ventricular conduction',
    definition: 'Delayed or blocked conduction down the left bundle branch, causing abnormal delayed left ventricular activation.',
    pathophysiology: 'The right ventricle activates first, then the impulse spreads slowly through myocardium to activate the left ventricle, changing depolarisation and repolarisation.',
    symptoms: ['Often asymptomatic', 'May indicate ischemia', 'May occur with cardiomyopathy', 'May reflect severe hypertension or ventricular dyssynchrony'],
    criteria: [
      { label: 'QRS duration', value: '0.12 seconds or more.' },
      { label: 'Lead V1', value: 'Deep wide negative QS or rS pattern.' },
      { label: 'Lead V6', value: 'Tall broad notched or slurred R wave with absent normal septal q wave.' },
      { label: 'ST-T changes', value: 'Discordant repolarisation: ST-T changes point opposite terminal QRS forces.' },
    ],
    pearls: [
      'LBBB can mimic infarction and makes ST-T interpretation more complex.',
      'New LBBB with ischemic symptoms should not be treated as a routine benign conduction finding.',
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'sinus-bradycardia',
    title: 'Sinus bradycardia',
    category: 'Sinus rhythm',
    definition: 'A regular rhythm originating from the SA node with a ventricular rate slower than 60 bpm.',
    pathophysiology: 'The SA node depolarises slowly. It can be benign in athletes or during sleep, but may also reflect inferior MI, beta-blockers, diltiazem, digoxin, or sick sinus syndrome.',
    symptoms: ['Often asymptomatic', 'Hypotension', 'Dizziness', 'Weakness', 'Cool or moist skin', 'Chest discomfort', 'Shortness of breath', 'Syncope'],
    criteria: [
      { label: 'Rhythm', value: 'Atrial and ventricular rhythms are regular.' },
      { label: 'Rate', value: 'Slower than 60 bpm.' },
      { label: 'P waves', value: 'Upright in lead II, uniform, and before every QRS in a 1:1 relationship.' },
      { label: 'PR interval', value: 'Constant and normal, 0.12 to 0.20 seconds.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'Sinus bradycardia is not automatically pathological; symptoms and context decide urgency.',
      'Inferior MI and rate-slowing drugs are important reversible or dangerous causes to consider.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'sinus-tachycardia',
    title: 'Sinus tachycardia',
    category: 'Sinus rhythm',
    definition: 'A regular rhythm originating from the SA node with a rate above 100 bpm.',
    pathophysiology: 'The SA node fires rapidly in response to sympathetic stimulation or reduced parasympathetic tone, commonly from exercise, fever, pain, dehydration, anxiety, hypoxia, or hypovolaemia.',
    symptoms: ['Palpitations', 'Chest tightness', 'Racing heart rate', 'Shortness of breath', 'Anxiety', 'Lightheadedness'],
    criteria: [
      { label: 'Rhythm', value: 'Atrial and ventricular rhythms are regular.' },
      { label: 'Rate', value: '101 to 180 bpm.' },
      { label: 'P waves', value: 'Upright in lead II and before each QRS in a 1:1 relationship.' },
      { label: 'PR interval', value: 'Normal, 0.12 to 0.20 seconds.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'Sinus tachycardia is usually a sign of an underlying driver, not the primary diagnosis.',
      'Very rapid rates shorten diastolic filling and may worsen ischemia or reduce stroke volume.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'sinus-arrhythmia',
    title: 'Sinus arrhythmia',
    category: 'Sinus rhythm',
    definition: 'A sinus rhythm with an irregular rate, usually phasic with respiration.',
    pathophysiology: 'Respiratory changes in vagal tone cause the heart rate to increase during inspiration and slow during expiration. It is common and benign in healthy children and young adults.',
    symptoms: ['None'],
    criteria: [
      { label: 'Rhythm', value: 'Irregular with cyclical acceleration and deceleration.' },
      { label: 'Rate', value: 'Usually 60 to 100 bpm, but may slow below 60 bpm during expiration.' },
      { label: 'P waves', value: 'Uniform, upright in lead II, and before each QRS.' },
      { label: 'PR interval', value: 'Normal and constant, 0.12 to 0.20 seconds.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'The key is gradual cyclic variability, not chaotic irregularity.',
      'Visible normal P waves before every QRS help separate it from AFib.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'sinoatrial-block',
    title: 'Sinoatrial block',
    category: 'Sinus node dysfunction',
    definition: 'A conduction disorder where the SA node generates an impulse but it fails to exit into atrial myocardium.',
    pathophysiology: 'The SA node fires on time, but the impulse is blocked at the sinoatrial junction. Because atria do not depolarise, an entire P-QRS-T cycle is dropped and the sinus rhythm resumes on schedule.',
    symptoms: ['Usually asymptomatic', 'Palpitations', 'Lightheadedness', 'Hypotension', 'Dizziness'],
    criteria: [
      { label: 'Rhythm', value: 'Regular except for the pause.' },
      { label: 'Rate', value: 'Varies with the underlying rhythm except during the block.' },
      { label: 'P waves', value: 'Normal on conducted beats and absent during the pause.' },
      { label: 'PR interval', value: 'Normal, 0.12 to 0.20 seconds, on conducted beats.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
      { label: 'Pause clue', value: 'The pause is an exact multiple of the underlying P-P interval.' },
    ],
    pearls: [
      'SA block drops a whole P-QRS-T cycle, not just a QRS.',
      'An exact multiple pause helps distinguish SA block from sinus arrest.',
    ],
    topicId: 'step.pWave',
  },
  {
    id: 'sinus-arrest',
    title: 'Sinus arrest',
    category: 'Sinus node dysfunction',
    definition: 'A disorder of impulse formation where the SA node fails to generate an electrical impulse.',
    pathophysiology: 'The SA node pauses unpredictably, causing a gap in cardiac electrical activity. If prolonged, a lower escape pacemaker may fire to rescue the heart.',
    symptoms: ['Lightheadedness', 'Weakness', 'Syncope', 'Chest pain with prolonged or frequent pauses'],
    criteria: [
      { label: 'Rhythm', value: 'Regular except for an unpredictable pause.' },
      { label: 'Rate', value: 'Varies with the underlying rhythm except during the pause.' },
      { label: 'P waves', value: 'Normal on conducted beats and absent during the pause.' },
      { label: 'PR interval', value: 'Normal, 0.12 to 0.20 seconds, on conducted beats.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
      { label: 'Pause clue', value: 'The pause is not an exact multiple of the underlying P-P interval.' },
    ],
    pearls: [
      'Sinus arrest is an impulse formation problem; SA block is an impulse exit problem.',
      'Long pauses may trigger junctional or ventricular escape beats.',
    ],
    topicId: 'step.pWave',
  },
  {
    id: 'junctional-escape-rhythm',
    title: 'Junctional escape rhythm',
    category: 'Junctional rhythm',
    definition: 'A protective regular escape rhythm originating in the AV junction at 40 to 60 bpm.',
    pathophysiology: 'The AV junction takes over when the SA node fails or impulses are blocked. Conduction travels retrograde to the atria and forward through the ventricles.',
    symptoms: ['Dizziness', 'Lightheadedness', 'Hypotension if rate is too slow'],
    criteria: [
      { label: 'Rhythm', value: 'Very regular.' },
      { label: 'Rate', value: '40 to 60 bpm.' },
      { label: 'P waves', value: 'May appear before, during, or after QRS; if visible, inverted in II, III, and aVF.' },
      { label: 'PR interval', value: 'Short, usually 0.12 seconds or less, if P wave precedes QRS; otherwise absent.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'Inverted inferior-lead P waves are a major clue to retrograde atrial activation.',
      'A junctional escape rhythm is protective, but symptoms depend on rate and cardiac output.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'accelerated-junctional-rhythm',
    title: 'Accelerated junctional rhythm',
    category: 'Junctional rhythm',
    definition: 'A regular AV-junction rhythm with a rate of 61 to 100 bpm.',
    pathophysiology: 'Abnormal automaticity in the AV junction or bundle of His allows the junction to fire faster than its intrinsic escape rate. Causes include digoxin toxicity, acute MI, and myocarditis.',
    symptoms: ['Typically asymptomatic and stable'],
    criteria: [
      { label: 'Rhythm', value: 'Very regular.' },
      { label: 'Rate', value: '61 to 100 bpm.' },
      { label: 'P waves', value: 'May be before, buried within, or after QRS; if visible, inverted in II, III, and aVF.' },
      { label: 'PR interval', value: 'Short, usually 0.12 seconds or less, when P precedes QRS.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'The rate separates accelerated junctional rhythm from junctional escape and junctional tachycardia.',
      'Think of digoxin effect or toxicity when junctional rhythms appear in the right context.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'junctional-tachycardia',
    title: 'Junctional tachycardia',
    category: 'Junctional rhythm',
    definition: 'A rapid supraventricular rhythm originating in the AV junction at 101 to 180 bpm.',
    pathophysiology: 'Highly abnormal automaticity or reentry in junctional tissue drives a rapid rhythm that shortens diastolic filling and can reduce cardiac output.',
    symptoms: ['Palpitations', 'Chest discomfort', 'Shortness of breath', 'Anxiety', 'Lightheadedness'],
    criteria: [
      { label: 'Rhythm', value: 'Regular.' },
      { label: 'Rate', value: '101 to 180 bpm.' },
      { label: 'P waves', value: 'May be before, buried within, or after QRS; if visible, inverted in II, III, and aVF.' },
      { label: 'PR interval', value: 'Short, usually 0.12 seconds or less, when P precedes QRS; otherwise absent.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'A narrow regular tachycardia with inverted or hidden P waves can be junctional.',
      'Symptoms come from rapid rate and reduced filling time.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'idioventricular-rhythm',
    title: 'Idioventricular rhythm',
    category: 'Ventricular rhythm',
    definition: 'A slow regular ventricular escape rhythm with a rate of 20 to 40 bpm.',
    pathophysiology: 'A ventricular focus acts as the last backup pacemaker. Because activation spreads slowly muscle-to-muscle, QRS complexes are wide and bizarre.',
    symptoms: ['Severe hemodynamic compromise', 'Profound hypotension', 'Dizziness', 'Confusion', 'Syncope', 'Loss of consciousness'],
    criteria: [
      { label: 'Rhythm', value: 'Essentially regular.' },
      { label: 'Rate', value: '20 to 40 bpm.' },
      { label: 'P waves', value: 'Absent or completely dissociated.' },
      { label: 'PR interval', value: 'None.' },
      { label: 'QRS complex', value: 'Wide and bizarre, 0.12 seconds or greater.' },
    ],
    pearls: [
      'This is a last-line escape rhythm and is often hemodynamically unstable.',
      'Wide QRS with very slow rate points to a ventricular origin.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'accelerated-idioventricular-rhythm',
    title: 'Accelerated idioventricular rhythm',
    category: 'Ventricular rhythm',
    definition: 'A regular ventricular rhythm with a rate of 41 to 100 bpm.',
    pathophysiology: 'Abnormal automaticity of ventricular pacemaker cells produces a faster ventricular rhythm. It is often transient and benign during reperfusion after acute MI treatment.',
    symptoms: ['Usually asymptomatic', 'Usually hemodynamically stable'],
    criteria: [
      { label: 'Rhythm', value: 'Essentially regular.' },
      { label: 'Rate', value: '41 to 100 bpm, with some references allowing up to 120 bpm.' },
      { label: 'P waves', value: 'Absent or completely dissociated.' },
      { label: 'PR interval', value: 'None.' },
      { label: 'QRS complex', value: 'Wide and bizarre, 0.12 seconds or greater.' },
    ],
    pearls: [
      'AIVR is commonly seen during reperfusion and is often transient.',
      'Rate helps distinguish AIVR from idioventricular rhythm and ventricular tachycardia.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'premature-atrial-complex',
    title: 'Premature atrial complex',
    category: 'Ectopic beats',
    definition: 'An early ectopic beat originating from irritable atrial tissue outside the SA node.',
    pathophysiology: 'A premature atrial impulse can be triggered by stress, stimulants, electrolyte imbalance, ischemia, or atrial stretch. It depolarises the atria early, conducts to the ventricles, resets the SA node, and often creates a non-compensatory pause.',
    symptoms: ['Often asymptomatic', 'Skipped-beat sensation', 'Fluttering in the chest', 'Transient palpitations'],
    criteria: [
      { label: 'Rhythm', value: 'Irregular because of the early ectopic beat.' },
      { label: 'Rate', value: 'Reflects the underlying sinus rate.' },
      { label: 'P waves', value: 'Premature P wave appears early and has a different morphology; it may be hidden in the preceding T wave.' },
      { label: 'PR interval', value: 'Usually normal but may differ from the sinus PR; very early PACs may conduct slowly or be blocked.' },
      { label: 'QRS complex', value: 'Usually normal duration unless conducted with aberrancy, often RBBB-like.' },
    ],
    pearls: [
      'A notched or distorted T wave may hide a premature atrial P wave.',
      'Blocked PACs can mimic sinus pause or AV block if the early P wave is missed.',
    ],
    topicId: 'step.pWave',
  },
  {
    id: 'premature-junctional-complex',
    title: 'Premature junctional complex',
    category: 'Ectopic beats',
    definition: 'An early ectopic beat originating from irritable tissue within the AV junction.',
    pathophysiology: 'A junctional focus fires before the next sinus impulse, sending activation backward to the atria and forward to the ventricles.',
    symptoms: ['Palpitations', 'Chest skips', 'Lightheadedness', 'Transient pause sensation'],
    criteria: [
      { label: 'Rhythm', value: 'Irregular during the premature event.' },
      { label: 'Rate', value: 'Reflects the underlying sinus rate.' },
      { label: 'P waves', value: 'May appear before, during, or after QRS; if visible, inverted in II, III, and aVF.' },
      { label: 'PR interval', value: 'Short, usually 0.12 seconds or less, if inverted P precedes QRS; absent if no P precedes QRS.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'Inverted inferior-lead P waves point to retrograde atrial activation.',
      'PJCs are less common than PACs and PVCs but follow the same premature-beat logic.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'premature-ventricular-complex',
    title: 'Premature ventricular complex',
    category: 'Ectopic beats',
    definition: 'An early ectopic beat originating from an irritable focus in the ventricular myocardium.',
    pathophysiology: 'A ventricular cell depolarises early and spreads slowly through ordinary myocardium instead of the His-Purkinje system, producing a wide distorted complex and usually a full compensatory pause.',
    symptoms: ['Palpitations', 'Flopping sensation in the chest', 'Sinking sensation', 'Weakness', 'Dizziness', 'Chest discomfort'],
    criteria: [
      { label: 'Rhythm', value: 'Irregular because of the premature ventricular beat.' },
      { label: 'Rate', value: 'Reflects the underlying sinus rate.' },
      { label: 'P waves', value: 'Absent before the premature QRS complex.' },
      { label: 'PR interval', value: 'None for the PVC.' },
      { label: 'QRS complex', value: 'Wide and bizarre, 0.12 seconds or greater, with discordant T wave.' },
    ],
    pearls: [
      'PVCs are ventricular until proven otherwise when the premature beat is wide, bizarre, and lacks a preceding P wave.',
      'PVCs landing on the T wave can create R-on-T risk in vulnerable repolarisation settings.',
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'sustained-monomorphic-vt',
    title: 'Sustained monomorphic VT',
    category: 'Ventricular rhythm',
    definition: 'A rapid life-threatening ventricular rhythm made of three or more consecutive PVC-like complexes of uniform shape above 100 bpm.',
    pathophysiology: 'Usually driven by ventricular reentry or abnormal automaticity, often around old myocardial scar. The rapid rate reduces ventricular filling, stroke volume, coronary perfusion, and cerebral blood flow.',
    symptoms: ['Dizziness', 'Syncope', 'Shortness of breath', 'Severe chest pain', 'Hypotension', 'Pulselessness', 'Cardiac arrest'],
    criteria: [
      { label: 'Rhythm', value: 'Essentially regular.' },
      { label: 'Rate', value: 'Ventricular rate 100 to 250 bpm.' },
      { label: 'P waves', value: 'Absent or dissociated from QRS complexes.' },
      { label: 'PR interval', value: 'None.' },
      { label: 'QRS complex', value: 'Wide and bizarre, 0.12 seconds or greater, with uniform morphology in a single lead.' },
    ],
    pearls: [
      'Wide-complex tachycardia in an unstable patient should be treated as VT until proven otherwise.',
      'Monomorphic means the QRS shape stays uniform, unlike torsades or polymorphic VT.',
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'atrial-tachycardia-with-block',
    title: 'Atrial tachycardia with block',
    category: 'Supraventricular rhythm',
    definition: 'A rapid atrial rhythm from a single ectopic focus, often with AV block.',
    pathophysiology: 'A single atrial focus fires rapidly and overrides the SA node. The AV node cannot conduct every atrial impulse, producing block ratios such as 2:1; digoxin toxicity with hypokalemia is a classic association.',
    symptoms: ['Palpitations', 'Fatigue', 'Lightheadedness', 'Chest fluttering', 'Dyspnea'],
    criteria: [
      { label: 'Rhythm', value: 'Atrial rhythm is regular; ventricular rhythm is regular with fixed block or irregular with variable block.' },
      { label: 'Rate', value: 'Atrial rate 150 to 250 bpm; ventricular rate is slower depending on block ratio.' },
      { label: 'P waves', value: 'Present but non-sinus in shape; may be pointed, small, or hidden in preceding T waves.' },
      { label: 'PR interval', value: 'Normal or prolonged on conducted beats.' },
      { label: 'QRS complex', value: 'Usually normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'Atrial tachycardia with block should make you think about digoxin effect or toxicity in the right clinical setting.',
      'Look carefully for atrial activity hidden in T waves before calling it another SVT.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'avnrt',
    title: 'AV nodal reentrant tachycardia',
    category: 'Supraventricular rhythm',
    definition: 'The most common paroxysmal SVT, caused by a rapid reentrant loop within the AV node.',
    pathophysiology: 'Dual AV nodal pathways can allow a PAC to trigger a self-sustaining reentry circuit, depolarising atria and ventricles nearly simultaneously.',
    symptoms: ['Sudden racing palpitations', 'Shortness of breath', 'Chest pressure', 'Dizziness', 'Polyuria', 'Syncope'],
    criteria: [
      { label: 'Rhythm', value: 'Extremely regular.' },
      { label: 'Rate', value: 'Usually 150 to 250 bpm.' },
      { label: 'P waves', value: 'Usually hidden in QRS; may create pseudo-S waves in inferior leads or pseudo-R prime in V1.' },
      { label: 'PR interval', value: 'Unmeasurable or extremely short.' },
      { label: 'QRS complex', value: 'Usually narrow, 0.11 seconds or less.' },
    ],
    pearls: [
      'Abrupt onset and termination are typical of paroxysmal SVT patterns.',
      'Hidden retrograde P waves are a key reason the rhythm can look like a narrow regular tachycardia with no P waves.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'right-ventricular-hypertrophy',
    title: 'Right ventricular hypertrophy',
    category: 'Chamber enlargement',
    definition: 'Pathological enlargement and thickening of the right ventricular muscular wall.',
    pathophysiology: 'Chronic right ventricular pressure overload, often from pulmonary hypertension, COPD, or pulmonic stenosis, shifts the net electrical vector anteriorly and to the right.',
    symptoms: ['Dyspnea on exertion', 'Fatigue', 'Chest pain', 'Peripheral edema', 'Jugular venous distention'],
    criteria: [
      { label: 'Axis', value: 'Right axis deviation, mean QRS axis greater than +90 degrees.' },
      { label: 'Lead V1', value: 'Tall dominant R wave equal to or greater than S wave height, R/S ratio >= 1.' },
      { label: 'Lead V6', value: 'Deep prominent S wave, R/S ratio < 1.' },
      { label: 'Repolarisation', value: 'Right ventricular strain pattern with asymmetric ST depression and T-wave inversion in V1 to V3.' },
    ],
    pearls: [
      'RVH interpretation depends on axis, precordial forces, and clinical context together.',
      'Pulmonary disease and pulmonary hypertension are common clinical clues.',
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'myocardial-ischemia',
    title: 'Myocardial ischemia',
    category: 'Ischemia and infarction',
    definition: 'A reversible restriction in myocardial blood supply that deprives heart muscle of oxygen and nutrients.',
    pathophysiology: 'Coronary flow temporarily fails to meet oxygen demand, often from atherosclerosis, coronary spasm, or transient thrombus. Ischemia delays repolarisation and alters ST-T vectors.',
    symptoms: ['Angina', 'Substernal pressure', 'Radiation to left arm, neck, or jaw', 'Shortness of breath', 'Diaphoresis', 'Nausea'],
    criteria: [
      { label: 'ST depression', value: 'Horizontal or downsloping ST depression of 0.5 mm or more in two or more contiguous leads.' },
      { label: 'T-wave changes', value: 'Symmetric T-wave inversion of 1 mm or more in contiguous leads.' },
    ],
    pearls: [
      'Ischemia is often a repolarisation diagnosis: ST depression and T-wave inversion are the core clues.',
      'Contiguous lead grouping and symptoms decide clinical significance.',
    ],
    topicId: 'step.stSegment',
  },
  {
    id: 'myocardial-injury',
    title: 'Myocardial injury',
    category: 'Ischemia and infarction',
    definition: 'An acute severe state of myocardial cellular distress indicating active injury from prolonged oxygen deprivation.',
    pathophysiology: 'Usually follows unresolved ischemia from sudden coronary occlusion. Partially depolarised injured cells create a current of injury that shifts the ST segment; rapid reperfusion can still prevent necrosis.',
    symptoms: ['Crushing substernal chest pain', 'Pain not relieved by rest or nitroglycerin', 'Dyspnea', 'Diaphoresis', 'Anxiety', 'Dizziness'],
    criteria: [
      { label: 'ST elevation', value: 'ST elevation of 1 mm or more at the J point in two or more contiguous leads, with V2-V3 using lead-specific thresholds.' },
      { label: 'Reciprocal changes', value: 'ST depression in anatomically opposite leads supports acute territorial injury.' },
    ],
    pearls: [
      'Injury is the ECG stage where rapid reperfusion can still prevent permanent necrosis.',
      'Reciprocal change and clinical symptoms raise urgency beyond isolated ST elevation alone.',
    ],
    topicId: 'step.stSegment',
  },
  {
    id: 'myocardial-infarction-necrosis',
    title: 'Myocardial infarction / necrosis',
    category: 'Ischemia and infarction',
    definition: 'Irreversible death and scarring of myocardial tissue after prolonged uncorrected ischemia and injury.',
    pathophysiology: 'Necrotic myocardium is electrically silent. Leads over the scar record vectors moving away from that region, producing deep negative Q-wave deflections.',
    symptoms: ['Prior severe chest pain episode', 'May be asymptomatic if old', 'Possible chronic heart failure symptoms'],
    criteria: [
      { label: 'Pathological Q waves', value: 'Q wave longer than 0.04 seconds and deeper than one-third of the succeeding R wave in two or more contiguous leads.' },
      { label: 'QRS changes', value: 'Loss of normal R-wave height progression in precordial leads can support infarction patterns.' },
    ],
    pearls: [
      'Pathological Q waves indicate necrosis or scar, not necessarily acute active injury.',
      'Territory and contiguous leads prevent overcalling isolated Q-wave variants.',
    ],
    topicId: 'step.qWaves',
  },
  {
    id: 'ventricular-fibrillation-condition',
    title: 'Ventricular fibrillation',
    category: 'Cardiac arrest rhythm',
    definition: 'A chaotic, disorganised, life-threatening ventricular arrhythmia with no coordinated electrical or mechanical cardiac activity.',
    pathophysiology: 'Multiple ectopic ventricular foci fire extremely rapidly and without coordination. The ventricles quiver instead of contracting, producing zero stroke volume, zero cardiac output, absent pulses, and immediate clinical death.',
    symptoms: ['Immediate loss of consciousness', 'Pulselessness', 'Apnea', 'Dilated pupils'],
    criteria: [
      { label: 'Rhythm', value: 'Completely chaotic, irregular, and uncoordinated.' },
      { label: 'Rate', value: 'Rapid and not measurable.' },
      { label: 'P waves', value: 'Completely absent.' },
      { label: 'PR interval', value: 'None.' },
      { label: 'QRS complex', value: 'Absent and replaced by erratic irregular fibrillatory waves; coarse VF is 3 mm or greater, fine VF is less than 3 mm.' },
    ],
    pearls: [
      'Always check the patient and leads, but true VF is a shockable cardiac arrest rhythm.',
      'Fine VF can be mistaken for asystole, so verify in more than one lead when possible without delaying resuscitation.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'asystole-condition',
    title: 'Asystole',
    category: 'Cardiac arrest rhythm',
    definition: 'Complete absence of ventricular electrical and mechanical activity, representing cardiac standstill.',
    pathophysiology: 'Ventricular depolarisation ceases completely, producing zero cardiac output and no pulse. Causes include terminal hypoxia, severe myocardial necrosis, profound electrolyte imbalance, and terminal drug toxicity.',
    symptoms: ['Unresponsive', 'Pulseless', 'Apneic', 'No measurable blood pressure'],
    criteria: [
      { label: 'Rhythm', value: 'None; flat line at the isoelectric baseline.' },
      { label: 'Rate', value: 'None.' },
      { label: 'P waves', value: 'Usually absent; isolated P waves may occasionally march out without QRS complexes.' },
      { label: 'PR interval', value: 'None.' },
      { label: 'QRS complex', value: 'Completely absent.' },
    ],
    pearls: [
      'Confirm asystole in at least two leads and check cables or gain before committing to the diagnosis.',
      'True asystole is not shockable; fine VF is the important mimic to exclude.',
    ],
    topicId: 'step.finalReview',
  },
  {
    id: 'wandering-atrial-pacemaker',
    title: 'Wandering atrial pacemaker',
    category: 'Supraventricular rhythm',
    definition: 'A benign supraventricular rhythm where the pacemaking focus shifts between the SA node, atrial sites, and sometimes the AV junction.',
    pathophysiology: 'The dominant pacemaker wanders among supraventricular sites, often due to vagal tone variation. It may be a normal variant in athletes or during sleep.',
    symptoms: ['Asymptomatic'],
    criteria: [
      { label: 'Rhythm', value: 'Irregular because pacemaker sites shift.' },
      { label: 'Rate', value: 'Usually 60 to 100 bpm, or slower when associated with sinus bradycardia.' },
      { label: 'P waves', value: 'At least three distinct P-wave morphologies in a single lead.' },
      { label: 'PR interval', value: 'Variable from beat to beat depending on pacemaker site.' },
      { label: 'QRS complex', value: 'Normal duration, 0.11 seconds or less.' },
    ],
    pearls: [
      'WAP is MAT-like in morphology, but the rate is not tachycardic.',
      'At least three different P-wave shapes are the key criterion.',
    ],
    topicId: 'step.pWave',
  },
  {
    id: 'atrioventricular-reentrant-tachycardia',
    title: 'Atrioventricular reentrant tachycardia',
    category: 'Supraventricular rhythm',
    definition: 'A paroxysmal SVT caused by a reentrant circuit involving the AV node and an accessory pathway.',
    pathophysiology: 'An accessory muscular bridge allows a circular pathway between atria and ventricles. Orthodromic AVRT travels down the AV node and returns via the accessory tract, while antidromic AVRT travels down the accessory tract and returns via the AV node.',
    symptoms: ['Sudden racing palpitations', 'Lightheadedness', 'Chest tightness', 'Anxiety', 'Syncope'],
    criteria: [
      { label: 'Rhythm', value: 'Extremely regular.' },
      { label: 'Rate', value: '150 to 250 bpm.' },
      { label: 'P waves', value: 'Retrograde P waves may be visible in the ST segment or early T wave, or hidden.' },
      { label: 'PR interval', value: 'Short or not measurable.' },
      { label: 'QRS complex', value: 'Narrow in orthodromic AVRT; wide in antidromic AVRT.' },
    ],
    pearls: [
      'Orthodromic AVRT is usually narrow; antidromic AVRT is wide because ventricular activation begins through the accessory pathway.',
      'A history or ECG evidence of WPW makes AVRT more likely.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'left-ventricular-hypertrophy',
    title: 'Left ventricular hypertrophy',
    category: 'Chamber enlargement',
    definition: 'Pathological thickening and enlargement of the left ventricular muscle wall.',
    pathophysiology: 'Chronic left ventricular pressure overload, commonly from systemic hypertension or aortic stenosis, increases left ventricular electrical forces and may shift the axis leftward.',
    symptoms: ['Dyspnea on exertion', 'Fatigue', 'Atypical chest pain', 'Palpitations', 'Heart failure symptoms'],
    criteria: [
      { label: 'Voltage', value: 'Marked QRS amplitude increase; S in V1 plus R in V5 or V6 of 35 mm or greater supports Sokolow-Lyon LVH criteria.' },
      { label: 'Axis', value: 'May show left axis deviation, often between -30 and -90 degrees.' },
      { label: 'Strain pattern', value: 'Asymmetric downsloping ST depression and T-wave inversion in lateral leads I, aVL, V5, and V6.' },
    ],
    pearls: [
      'Voltage criteria alone are imperfect; strain pattern and clinical context increase confidence.',
      'LVH can produce secondary ST-T changes that mimic ischemia.',
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'right-atrial-abnormality',
    title: 'Right atrial abnormality',
    category: 'Chamber enlargement',
    definition: 'Pathological dilation or hypertrophy of the right atrial chamber, often called P-pulmonale.',
    pathophysiology: 'Right atrial pressure overload from COPD, emphysema, pulmonary hypertension, or right-sided heart disease increases the first half of the P wave because the right atrium depolarises first.',
    symptoms: ['Chronic dyspnea', 'Fatigue', 'Productive cough', 'Peripheral edema', 'Right-sided heart failure symptoms'],
    criteria: [
      { label: 'Inferior leads', value: 'Tall, peaked, symmetrical P waves in II, III, and aVF with amplitude greater than 2.5 mm.' },
      { label: 'P-wave duration', value: 'Usually normal, 0.11 seconds or less.' },
      { label: 'V1/V2', value: 'Tall upright P wave exceeding 1.5 mm.' },
    ],
    pearls: [
      'RAA changes P-wave height more than width.',
      'Think pulmonary disease or pulmonary hypertension when P-pulmonale appears.',
    ],
    topicId: 'step.pWave',
  },
  {
    id: 'left-atrial-abnormality',
    title: 'Left atrial abnormality',
    category: 'Chamber enlargement',
    definition: 'Pathological dilation or hypertrophy of the left atrial chamber, often called P-mitrale.',
    pathophysiology: 'Left atrial overload from mitral valve disease, systemic hypertension, or left ventricular failure prolongs and splits the terminal left atrial portion of the P wave.',
    symptoms: ['Dyspnea', 'Orthopnea', 'Paroxysmal nocturnal dyspnea', 'Fatigue', 'Palpitations', 'Increased atrial fibrillation risk'],
    criteria: [
      { label: 'P-wave duration', value: 'Prolonged P wave in limb leads, especially lead II, exceeding 0.12 seconds.' },
      { label: 'Lead II morphology', value: 'Wide, notched, or double-humped P wave with notch spacing greater than 0.04 seconds.' },
      { label: 'Lead V1', value: 'Biphasic P wave with terminal negative component at least 1 mm wide and 1 mm deep.' },
    ],
    pearls: [
      'LAA changes P-wave width and terminal negativity more than height.',
      'Left atrial abnormality is a useful clue to mitral disease, hypertension, LV failure, and future AF risk.',
    ],
    topicId: 'step.pWave',
  },
  {
    id: 'acute-pericarditis',
    title: 'Acute pericarditis',
    category: 'Ischemia and infarction',
    definition: 'Acute inflammation of the pericardial sac surrounding the heart.',
    pathophysiology: 'Epicardial and pericardial inflammation produces diffuse subepicardial injury, creating widespread ECG changes rather than a single coronary territory pattern.',
    symptoms: ['Sharp substernal chest pain', 'Pain radiating to back or left shoulder', 'Pain worse with inspiration or lying flat', 'Pain relieved by sitting forward', 'Possible friction rub'],
    criteria: [
      { label: 'ST elevation', value: 'Diffuse concave-upward ST elevation across most leads except aVR and often V1.' },
      { label: 'PR segment', value: 'Diffuse PR depression with reciprocal PR elevation in aVR.' },
      { label: 'Reciprocal ST changes', value: 'ST depression is confined to aVR and sometimes V1, without territorial reciprocal depression.' },
    ],
    pearls: [
      'Diffuse ST elevation plus PR depression points away from focal STEMI.',
      'Pericarditis pain is classically positional and pleuritic.',
    ],
    topicId: 'step.stSegment',
  },
  {
    id: 'severe-hyperkalemia-condition',
    title: 'Severe hyperkalemia',
    category: 'Electrolyte pattern',
    definition: 'A life-threatening metabolic emergency caused by elevated serum potassium, especially above 6.5 mEq/L.',
    pathophysiology: 'Excess extracellular potassium moves cardiac cells closer to threshold, slowing intraventricular conduction and accelerating repolarisation. Untreated severe hyperkalemia can progress to VF, asystole, and death.',
    symptoms: ['Muscle weakness', 'Fatigue', 'Paresthesias', 'Nausea', 'Flaccid paralysis', 'Bradycardia', 'Sudden cardiovascular collapse'],
    criteria: [
      { label: 'T waves', value: 'Tall, peaked, symmetric, narrow tented T waves diffusely across multiple leads.' },
      { label: 'P waves', value: 'Flattened, widened, and may disappear as severity increases.' },
      { label: 'PR interval', value: 'Prolonged.' },
      { label: 'QRS width', value: 'Widened QRS; extreme cases merge QRS and T waves into a sine-wave pattern.' },
    ],
    pearls: [
      'Hyperkalemia T waves are narrow, tented, and often diffuse.',
      'QRS widening in suspected hyperkalemia is an emergency pattern.',
    ],
    topicId: 'step.tWaves',
  },
  {
    id: 'hypokalemia',
    title: 'Hypokalemia',
    category: 'Electrolyte pattern',
    definition: 'A common electrolyte disorder caused by low serum potassium below 3.5 mEq/L.',
    pathophysiology: 'Low potassium delays myocardial repolarisation, reducing T-wave amplitude and making late Purkinje repolarisation visible as U waves. Common causes include loop diuretics and gastrointestinal losses.',
    symptoms: ['Muscle cramps', 'Weakness', 'Fatigue', 'Constipation', 'Palpitations', 'Hyporeflexia', 'Increased digoxin toxicity susceptibility'],
    criteria: [
      { label: 'T waves', value: 'Flattened, low-amplitude, or inverted T waves in multiple leads.' },
      { label: 'ST segment', value: 'Mild ST-segment depression.' },
      { label: 'U waves', value: 'Prominent rounded U waves after the T wave, often tallest in V2 and V3.' },
      { label: 'QT interval', value: 'Apparent QT prolongation from T-U fusion rather than true isolated QT prolongation.' },
    ],
    pearls: [
      'Prominent U waves plus flat T waves should prompt potassium correlation.',
      'Do not accidentally include large U waves as the T-wave end when measuring QT.',
    ],
    topicId: 'step.lateWaves',
  },
  {
    id: 'ventricular-paced-rhythm',
    title: 'Ventricular paced rhythm',
    category: 'Pacemaker rhythm',
    definition: 'A regular, artificially paced ventricular rhythm driven by an implanted or temporary electronic pacemaker.',
    pathophysiology: 'When intrinsic pacemaker cells fail to fire or conduct reliably, a pacemaker delivers an electrical stimulus directly to the ventricular myocardium. This bypasses the fast His-Purkinje system, so ventricular depolarisation spreads slowly cell to cell and produces a wide QRS complex.',
    symptoms: ['Usually haemodynamically stable', 'Prevents syncope', 'Prevents dizziness', 'Prevents profound bradycardia'],
    criteria: [
      { label: 'Pacemaker spike', value: 'Sharp, narrow, vertical pacing spike immediately before each paced QRS complex.' },
      { label: 'QRS complex', value: 'Wide, 0.12 seconds or greater, with a bizarre morphology that often resembles LBBB because right ventricular pacing is common.' },
      { label: 'T wave', value: 'Discordant to the main QRS deflection.' },
    ],
    pearls: [
      'A spike followed by a wide QRS supports normal ventricular capture.',
      'Secondary ST-T changes are expected in paced rhythms and should be interpreted with pacing context.',
    ],
    topicId: 'step.qrs',
  },
  {
    id: 'pacemaker-failure-to-capture',
    title: 'Pacemaker failure to capture',
    category: 'Pacemaker malfunction',
    definition: 'A critical pacemaker malfunction where the artificial stimulus fires but fails to depolarise the myocardium.',
    pathophysiology: 'The pacemaker generates a visible spike, but the delivered current does not trigger atrial or ventricular depolarisation. Causes include lead dislodgement, fibrosis at the electrode tip, battery depletion, severe hyperkalemia, or class I antiarrhythmic toxicity.',
    symptoms: ['Bradycardia', 'Syncope', 'Near-syncope', 'Profound hypotension', 'Dizziness', 'Extreme fatigue', 'Shortness of breath'],
    criteria: [
      { label: 'Pacemaker spikes', value: 'Sharp vertical pacing spikes are visible on the ECG.' },
      { label: 'Absent capture', value: 'One or more pacing spikes are not followed by the expected QRS complex for ventricular pacers or P wave for atrial pacers.' },
    ],
    pearls: [
      'A pacemaker spike without the expected following chamber depolarisation is the key pattern.',
      'Severe hyperkalemia can raise capture thresholds and cause apparent device malfunction.',
    ],
    topicId: 'step.finalReview',
  },
  {
    id: 'pacemaker-failure-to-sense',
    title: 'Pacemaker failure to sense',
    category: 'Pacemaker malfunction',
    definition: 'A pacemaker malfunction where the generator fails to detect the heart’s native electrical activity.',
    pathophysiology: 'Under-sensing causes the device to miss native P or QRS complexes, so it fires pacing spikes inappropriately throughout the cardiac cycle. A spike landing on the vulnerable downslope of a native T wave can trigger R-on-T degeneration into ventricular fibrillation.',
    symptoms: ['Palpitations', 'Skipped beats', 'Chest fluttering', 'Dizziness', 'Syncope', 'Cardiac arrest if VF is triggered'],
    criteria: [
      { label: 'Random spikes', value: 'Pacing spikes appear scattered irregularly across the strip and do not respect native depolarisations.' },
      { label: 'Inappropriate timing', value: 'Spikes may fall within native QRS complexes, ST segments, or T waves.' },
    ],
    pearls: [
      'Failure to sense is about inappropriate timing, not absence of pacing spikes.',
      'Pacing spikes on T waves are dangerous because they may trigger malignant ventricular arrhythmia.',
    ],
    topicId: 'step.finalReview',
  },
  {
    id: 'agonal-rhythm',
    title: 'Agonal rhythm',
    category: 'Cardiac arrest rhythm',
    definition: 'A terminal, highly irregular, extremely slow ventricular escape rhythm seen during the final stages of resuscitation or dying.',
    pathophysiology: 'As the SA node, AV node, and bundle branches fail, isolated ventricular cells fire sporadically at an extremely slow rate. Cardiac output is virtually absent, so the patient is clinically in cardiac arrest.',
    symptoms: ['Unresponsive', 'Pulseless', 'Apnoea', 'Agonal gasping respirations'],
    criteria: [
      { label: 'Rate', value: 'Extremely slow, usually less than 20 bpm; often only three or four beats on a 6-second strip.' },
      { label: 'Rhythm', value: 'Highly irregular and terminal appearing.' },
      { label: 'QRS complex', value: 'Very wide, slurred, bizarre complexes that may progressively lose distinct boundaries before asystole.' },
    ],
    pearls: [
      'Agonal rhythm is a cardiac arrest rhythm, not a perfusing bradycardia.',
      'Treat the patient and pulse status first; the ECG pattern signals terminal electrical failure.',
    ],
    topicId: 'step.rhythm',
  },
  {
    id: 'posterior-myocardial-infarction',
    title: 'Posterior myocardial infarction',
    category: 'Ischemia and infarction',
    definition: 'An acute or historical myocardial infarction involving the posterior wall of the left ventricle.',
    pathophysiology: 'Posterior MI is commonly caused by left circumflex or distal right coronary artery occlusion. Because standard 12-lead electrodes do not directly overlie the posterior wall, anterior leads V1 to V3 record mirror-image reciprocal changes instead of direct posterior ST elevation.',
    symptoms: ['Severe retrosternal chest pain', 'Pain radiating to the back or shoulder', 'Dyspnea', 'Diaphoresis', 'Anxiety'],
    criteria: [
      { label: 'V1 to V3', value: 'Horizontal ST-segment depression representing the mirror image of posterior ST elevation.' },
      { label: 'Tall R waves', value: 'Tall, broad R waves in V1 or V2, often with R/S ratio of 1 or greater, mirroring posterior Q waves.' },
      { label: 'Posterior leads', value: 'Confirmation is ST elevation of 0.5 mm or greater in V7, V8, and V9.' },
    ],
    pearls: [
      'Anterior ST depression in V1 to V3 with tall R waves should trigger a posterior lead check.',
      'Posterior MI can be missed if V7 to V9 are not recorded.',
    ],
    topicId: 'step.stSegment',
  },
  {
    id: 'right-ventricular-myocardial-infarction',
    title: 'Right ventricular myocardial infarction',
    category: 'Ischemia and infarction',
    definition: 'An acute infarction of the right ventricular free wall, often occurring with inferior wall MI.',
    pathophysiology: 'Proximal right coronary artery occlusion can deprive the right ventricle of blood supply. The resulting fall in right ventricular stroke volume makes the patient preload dependent, so nitrates or diuretics can precipitate severe hypotension.',
    symptoms: ['Acute chest pain', 'Hypotension', 'Clear lung fields', 'Jugular venous distention', 'Dyspnea', 'Diaphoresis'],
    criteria: [
      { label: 'Inferior STEMI', value: 'ST elevation of 1 mm or greater in II, III, and aVF.' },
      { label: 'Lead III greater than II', value: 'ST elevation in lead III is often greater than lead II, suggesting RCA involvement.' },
      { label: 'Right-sided lead', value: 'Confirmation is ST elevation in V4R, commonly 0.5 mm or greater, or 1 mm or greater in males.' },
    ],
    pearls: [
      'Inferior STEMI plus hypotension and clear lungs should raise RVMI concern.',
      'Avoid preload-reducing drugs until right ventricular involvement is assessed clinically.',
    ],
    topicId: 'step.stSegment',
  },
  {
    id: 'hypercalcemia',
    title: 'Hypercalcemia',
    category: 'Electrolyte pattern',
    definition: 'An electrolyte imbalance caused by abnormally elevated serum calcium.',
    pathophysiology: 'High calcium accelerates phase 2 of the cardiac action potential, shortening ventricular depolarisation and early repolarisation time.',
    symptoms: ['Muscle weakness', 'Bone pain', 'Renal stones', 'Constipation', 'Nausea', 'Vomiting', 'Confusion', 'Coma in severe cases'],
    criteria: [
      { label: 'QT interval', value: 'Shortened QTc, often 390 ms or less.' },
      { label: 'ST segment', value: 'Very short or nearly absent ST segment, with the T wave beginning soon after QRS termination.' },
    ],
    pearls: [
      'Short QT from a shortened ST segment is the key ECG clue.',
      'Hypercalcemia is a major metabolic cause of pathologically short QT.',
    ],
    topicId: 'step.qtInterval',
  },
  {
    id: 'hypocalcemia',
    title: 'Hypocalcemia',
    category: 'Electrolyte pattern',
    definition: 'An electrolyte imbalance caused by abnormally low serum calcium.',
    pathophysiology: 'Low calcium prolongs phase 2 of the cardiac action potential, stretching the plateau phase and delaying ventricular repolarisation.',
    symptoms: ['Paresthesias', 'Muscle cramps', 'Hyperreflexia', 'Tetany', 'Chvostek sign', 'Laryngeal spasm'],
    criteria: [
      { label: 'QT interval', value: 'Prolonged QTc, commonly greater than 0.46 seconds in females or greater than 0.45 seconds in males.' },
      { label: 'ST segment', value: 'Flat, pathologically prolonged ST segment while the T wave remains relatively normal in duration and shape.' },
    ],
    pearls: [
      'Hypocalcemia prolongs QT mainly by prolonging the ST segment.',
      'QT prolongation from hypocalcemia should be separated from drug or potassium-related repolarisation risk.',
    ],
    topicId: 'step.qtInterval',
  },
  {
    id: 'pulmonary-embolism-s1q3t3',
    title: 'Pulmonary embolism ECG pattern',
    category: 'Right heart strain',
    definition: 'ECG changes caused by acute pulmonary arterial obstruction and sudden right ventricular strain.',
    pathophysiology: 'A pulmonary embolus abruptly increases pulmonary vascular resistance. The right ventricle dilates and strains against this pressure load, producing right-sided electrical and repolarisation changes.',
    symptoms: ['Sudden dyspnea', 'Pleuritic chest pain', 'Tachycardia', 'Tachypnea', 'Cough', 'Hemoptysis', 'Syncope'],
    criteria: [
      { label: 'Most common finding', value: 'Sinus tachycardia, which is sensitive but non-specific.' },
      { label: 'S1Q3T3 pattern', value: 'Deep S wave in lead I, Q wave in lead III, and T-wave inversion in lead III.' },
      { label: 'Right heart strain', value: 'May show right axis deviation, new RBBB, or anterior/inferior T-wave inversion.' },
    ],
    pearls: [
      'A normal ECG does not exclude pulmonary embolism.',
      'S1Q3T3 is classic but not sensitive; right heart strain context matters more.',
    ],
    topicId: 'step.axis',
  },
  {
    id: 'advanced-second-degree-av-block',
    title: 'Advanced second-degree AV block',
    category: 'AV block',
    definition: 'A severe conduction block where two or more consecutive sinus P waves fail to conduct to the ventricles.',
    pathophysiology: 'High-grade AV block is often infranodal, within the His bundle or bundle branches. Multiple consecutive impulses fail to reach the ventricles, creating severe bradycardia and a high risk of complete heart block or ventricular standstill.',
    symptoms: ['Severe bradycardia', 'Chest pain', 'Dyspnea', 'Hypotension', 'Altered mental status', 'Near-syncope', 'Sudden cardiovascular collapse'],
    criteria: [
      { label: 'Conduction ratio', value: 'Fixed high-grade ratios such as 3:1, 4:1, or higher, with several P waves for each QRS complex.' },
      { label: 'Conducted PR', value: 'PR interval remains fixed for conducted beats, unlike third-degree AV block where PR relationships vary independently.' },
      { label: 'Risk', value: 'High risk of progression to complete AV block or ventricular standstill.' },
    ],
    pearls: [
      'High-grade AV block is clinically unstable until proven otherwise.',
      'Fixed PR intervals in conducted beats help separate advanced second-degree block from complete AV dissociation.',
    ],
    topicId: 'step.prInterval',
  },
];

export const ecgStudySteps: EcgStudyStep[] = [
  {
    step: 1,
    title: 'Rate',
    focus: 'Use ECG grid timing to calculate separate atrial and ventricular rates.',
    topicId: 'step.heartRate',
    checkpoints: ['Confirm 25 mm/s paper speed', 'Use R-R for ventricular rate', 'Use P-P for atrial rate', 'Choose 1500, sequence, or 6-second method'],
    clinicalPearl: 'Regular rhythms can use the 1500 or sequence method; irregular rhythms need the 6-second method, with atrial and ventricular rates recorded separately when they differ.',
  },
  {
    step: 2,
    title: 'P waves',
    focus: 'Evaluate atrial depolarization by checking P-wave presence, size, width, shape, direction, and QRS relationship.',
    topicId: 'step.pWave',
    checkpoints: ['Measure height and duration', 'Check expected lead deflections', 'Look for atrial abnormality patterns', 'Identify ectopic, flutter, fibrillatory, or paced atrial activity'],
    clinicalPearl: 'P-wave morphology often tells you whether atrial activation is sinus, enlarged, ectopic, retrograde, chaotic, or paced before the rhythm is formally named.',
  },
  {
    step: 3,
    title: 'PR and AV conduction',
    focus: 'Measure PR timing and classify AV conduction as normal, delayed, intermittently blocked, or dissociated.',
    topicId: 'step.prInterval',
    checkpoints: ['Measure P onset to QRS onset', 'Classify short, normal, or prolonged PR', 'Compare conducted PR intervals', 'Identify dropped QRS and AV dissociation'],
    clinicalPearl: 'The PR pattern matters as much as the PR number: progressive lengthening, fixed conducted PR with dropped beats, 2:1 conduction, and complete dissociation mean different risks.',
  },
  {
    step: 4,
    title: 'Rhythm synthesis',
    focus: 'Combine the first three steps into a rule-based rhythm differential.',
    topicId: 'step.rhythm',
    checkpoints: ['Classify ventricular regularity', 'Compare A:V ratio', 'Interpret P-wave vector', 'Track PR behavior', 'Use pacemaker rate ranges'],
    clinicalPearl: 'A rhythm diagnosis should be explainable from its inputs: regularity, P-wave morphology, PR behavior, conduction ratio, rate, and QRS width.',
  },
  {
    step: 5,
    title: 'QRS complex',
    focus: 'Measure ventricular depolarization and classify conduction, voltage, transition, and ventricular-origin patterns.',
    topicId: 'step.qrs',
    checkpoints: ['Measure widest QRS to the J point', 'Name QRS deflections correctly', 'Assess transition zone', 'Check BBB, hypertrophy, low voltage, and ventricular-origin clues'],
    clinicalPearl: 'QRS width and morphology change how later ST-T, QT, axis, and infarct findings should be interpreted.',
  },
  {
    step: 6,
    title: 'Axis',
    focus: 'Use the hexaxial limb-lead system to estimate frontal-plane QRS direction and explain axis shifts.',
    topicId: 'step.axis',
    checkpoints: ['Apply lead I and aVF quadrant logic', 'Use lead II to confirm LAD', 'Estimate degrees with equiphasic leads', 'Cross-check with QRS morphology and Q waves'],
    clinicalPearl: 'Axis is a directional clue: it becomes clinically useful when paired with QRS width, hypertrophy evidence, fascicular patterns, and infarct territories.',
  },
  {
    step: 7,
    title: 'Q waves',
    focus: 'Separate physiological septal Q waves from pathological scar patterns and pseudo-infarct mimics.',
    topicId: 'step.qWaves',
    checkpoints: ['Exclude aVR and normal variants', 'Measure Q-wave width and depth', 'Require contiguous lead grouping', 'Cross-check WPW, LBBB, LVH, and lead placement'],
    clinicalPearl: 'Pathological Q waves are scar clues, not automatic MI labels; territory grouping and QRS/pre-excitation context prevent pseudo-infarct errors.',
  },
  {
    step: 8,
    title: 'ST segment',
    focus: 'Measure J-point deviation against the correct baseline and localize injury, ischemia, or mimics.',
    topicId: 'step.stSegment',
    checkpoints: ['Choose TP or PR baseline', 'Measure at the J point', 'Apply territory thresholds', 'Check reciprocal, posterior, RV, and mimic patterns'],
    clinicalPearl: 'ST deviation is only as meaningful as its context: lead territory, morphology, reciprocal change, QRS pattern, serial change, and symptoms decide urgency.',
  },
  {
    step: 9,
    title: 'T waves',
    focus: 'Assess ventricular repolarization by T-wave direction, amplitude, shape, territory, and QRS context.',
    topicId: 'step.tWaves',
    checkpoints: ['Check expected lead deflection', 'Separate peaked from hyperacute morphology', 'Look for inversion, flattening, notching, and hidden P waves', 'Account for BBB, pacing, and ventricular rhythms'],
    clinicalPearl: 'T waves sit in an electrically vulnerable part of the cycle; hyperacute changes, R-on-T beats, and electrolyte patterns can matter before dramatic ST changes appear.',
  },
  {
    step: 10,
    title: 'QT interval',
    focus: 'Measure total ventricular electrical activity and correct it for heart rate to assess repolarization safety.',
    topicId: 'step.qtInterval',
    checkpoints: ['Measure QRS onset to T-wave end', 'Use the same clear lead for comparisons', 'Apply QTc correction and half-R-R screen', 'Check drugs, electrolytes, ischemia, CNS events, and short QT causes'],
    clinicalPearl: 'QTc above 500 ms is a major torsades risk threshold; short QT can be just as diagnostic when hypercalcemia or digoxin effect is present.',
  },
  {
    step: 11,
    title: 'Late waves and U waves',
    focus: 'Review R-wave progression and late deflections, especially true U waves after the T wave.',
    topicId: 'step.lateWaves',
    checkpoints: ['Check precordial transition', 'Identify a true U wave after baseline return', 'Classify prominent versus inverted U waves', 'Separate U waves from notched T waves or hidden P waves'],
    clinicalPearl: 'Prominent U waves point toward electrolyte or drug effects; inverted U waves in V2-V5 are pathological and should raise ischemia or severe hypertension concern.',
  },
  {
    step: 12,
    title: 'Final review and cross-validation',
    focus: 'Verify tracing quality, integrate clinical context, and catch logic conflicts before AI interpretation.',
    topicId: 'step.finalReview',
    checkpoints: ['Confirm calibration and aVR placement clues', 'Assess artifact before subtle ST-T-U calls', 'Add symptoms, drugs, electrolytes, and prior ECGs', 'Audit AV, wide-QRS, and contiguous-lead logic'],
    clinicalPearl: 'The final review is the safety gate: a confident ECG label is only useful when the tracing quality, patient context, and internal logic all agree.',
  },
];
